# Generated by Django 4.2.5 on 2023-10-13 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0006_alter_post_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publish',
        ),
    ]
